In [9]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
data = load_digits()
X, y = data.data, data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("Training Data:")
print(X_train)
print("Testing Data:")
print(x_test)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
nn_model = MLPClassifier(hidden_layer_sizes=(100, 100), max_iter=500, random_state=42)
nn_model.fit(X_train_scaled, y_train)
y_pred_nn = nn_model.predict(X_test_scaled)
nn_accuracy = accuracy_score(y_test, y_pred_nn)
logistic_model = LogisticRegression(max_iter=500)
logistic_model.fit(X_train_scaled, y_train)
y_pred_logistic = logistic_model.predict(X_test_scaled)
logistic_accuracy = accuracy_score(y_test, y_pred_logistic)
svm_model = SVC(kernel='linear')
svm_model.fit(X_train_scaled, y_train)
y_pred_svm = svm_model.predict(X_test_scaled)
svm_accuracy = accuracy_score(y_test, y_pred_svm)
dt_model = DecisionTreeClassifier(max_depth=10, random_state=42)
dt_model.fit(X_train_scaled, y_train)
y_pred_dt = dt_model.predict(X_test_scaled)
dt_accuracy = accuracy_score(y_test, y_pred_dt)
print("Comparison of Models:")
print(f"Neural Network Accuracy: {nn_accuracy}")
print(f"Logistic Regression Accuracy: {logistic_accuracy}")
print(f"SVM Accuracy: {svm_accuracy}")
print(f"Decision Tree Accuracy: {dt_accuracy}")

Training Data:
[[ 0.  0.  3. ... 13.  4.  0.]
 [ 0.  0.  9. ...  3.  0.  0.]
 [ 0.  0.  0. ...  6.  0.  0.]
 ...
 [ 0.  0.  9. ... 16.  2.  0.]
 [ 0.  0.  1. ...  0.  0.  0.]
 [ 0.  0.  1. ...  1.  0.  0.]]
Testing Data:
[[-3.05358035  9.12520872]
 [-6.75152278 -7.56116125]
 [-7.45526502 -6.75809978]
 [-7.10059136 -6.85322375]
 [-6.43961274 -7.38216382]
 [ 2.76908692  1.6216562 ]
 [ 5.25404554  2.73067739]
 [-5.33212199 -5.08423192]
 [-2.43939554  8.62897253]
 [ 3.67495538  2.65922114]
 [-7.50444577 -6.85401854]
 [-3.77008158  9.93214808]
 [-6.69286043 -7.63549253]
 [-8.46353001 -6.11969494]
 [-6.28652593 -7.18965603]
 [-6.30985991 -6.43240103]
 [-5.48027175 -5.95547591]
 [ 4.60712557  1.42974491]
 [-6.92521321 -6.63677014]
 [ 5.67741878  1.46315329]
 [-6.74665752 -7.58023041]
 [-3.4172217   7.60198243]
 [-0.64342311  9.48811905]
 [-7.36906663 -5.83594872]
 [-1.69568041  7.78342181]
 [ 4.9507864   3.4485259 ]
 [ 4.30409414  3.64219121]
 [ 6.48883493  3.09973471]
 [-2.39568028  9.676416